@extends('jsb.layouts.app')

@section('title', 'Order Preview')

@section('content')
    <div class="container-small cart py-3" style="margin-top: 1rem !important;">
        <nav class="mb-3" aria-label="breadcrumb">
            <ol class="breadcrumb mb-0">
                <li class="breadcrumb-item"><a href="{{ base_url() }}">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Orders Preview</li>
            </ol>
        </nav>

        <h2 class="mb-3">Orders Preview</h2>
        <div class="row mb-2">
            <div class="col-12 col-lg-12">
                <p style="font-size: 93%;">Below is the Orders Preview of EPDA for your good vessel calling the selected port generated by Port Quanta system. Appreciate to review carefully.<br>The Orders Preview of EPDA is temporarily live in the system and not processed yet.</p> 
            </div>
        </div>
        <div class="row g-5">
            <div class="col-12 col-lg-12">
                <div id="cartTable">
                    <div class="table-responsive scrollbar mx-n1 px-1">
                        <table class="table fs--1 mb-0 border-top border-200">
                            <thead>
                                <tr>
                                    <!-- <th class="sort white-space-nowrap align-middle fs--2" scope="col"></th> -->
                                    <th class="sort align-middle" scope="col">Document #</th>
                                    <th class="sort white-space-nowrap align-middle" scope="col" style="min-width:120px;">Port</th>
                                    <th class="sort align-middle" scope="col">Date Created</th>
                                    <th class="sort align-middle" scope="col">Currency</th>
                                    <th class="sort align-middle" scope="col">Total</th>
                                    <th class="sort text-end align-middle pe-0" scope="col"></th>
                                    <th class="sort text-end align-middle pe-0" scope="col"></th>
                                </tr>
                            </thead>
                            <tbody class="list" id="cart-table-body">
                                @php $grandTotalIDR = 0; @endphp
                                @php $grandTotalUSD = 0; @endphp
                                @if(isset($ctlCarts->CART_DATA))
                                    @foreach ($ctlCarts->CART_DATA as $value)
                                        <?php
                                        $totalIDR = ($value->CART_VALUE_CURRENCY_BASE > $value->CART_VALUE_CURRENCY_FOREIGN) ? $value->CART_VALUE_CURRENCY_BASE : $value->CART_VALUE_CURRENCY_FOREIGN;
                                        $totalUSD = ($value->CART_VALUE_CURRENCY_BASE < $value->CART_VALUE_CURRENCY_FOREIGN) ? $value->CART_VALUE_CURRENCY_BASE : $value->CART_VALUE_CURRENCY_FOREIGN;
                                        $displayTotal = $value->SALES_ORDER_DATA->CURRENCY_ID == "IDR" ? $totalIDR : $totalUSD;
                                        ?>
                                        <tr class="cart-table-row btn-reveal-trigger">
                                            <script type="text/javascript">
                                                var rowData_{{ md5($value->{"CART_ID"}) }} = {
                                                    "ID_HASHED" : "{{ md5($value->{"CART_ID"}) }}",
                                                    "CART_ID" : {{ $value->{"CART_ID"}  }},
                                                    "CART_SESSION" : "{{ $value->{"CART_SESSION"} }}",
                                                    "PORT_ID" : "{{ $value->{"PORT_DATA"}->{"PORT_ID"} }}",
                                                    "PORT_NAME" : "{{ $value->{"PORT_DATA"}->{"PORT_NAME"} }}",
                                                    "SO_VESSEL_NAME" : "{{ $value->{"SALES_ORDER_DATA"}->{"SO_VESSEL_NAME"} }}",
                                                    "SO_VESSEL_FLAG" : "{{ $value->{"SALES_ORDER_DATA"}->{"SO_VESSEL_FLAG"} }}",
                                                    "SO_VESSEL_COUNTRY" : "{{ $value->{"SALES_ORDER_DATA"}->{"SO_VESSEL_COUNTRY"} }}",
                                                    "SO_VESSEL_DWT" : {{ $value->{"SALES_ORDER_DATA"}->{"SO_VESSEL_DWT"} }},
                                                    "SO_VESSEL_GRT" : {{ $value->{"SALES_ORDER_DATA"}->{"SO_VESSEL_GRT"} }},
                                                    "SO_VESSEL_LOA" : {{ $value->{"SALES_ORDER_DATA"}->{"SO_VESSEL_LOA"} }},
                                                    "SO_OPERATION" : "{{ $value->{"SALES_ORDER_DATA"}->{"SO_OPERATION"} }}",
                                                    "SO_VESSEL_SHIPMENT" : "{{ $value->{"SALES_ORDER_DATA"}->{"SO_VESSEL_SHIPMENT"} }}",
                                                    "SO_VOYAGE_NO" : "{{ $value->{"SALES_ORDER_DATA"}->{"SO_VOYAGE_NO"} }}",
                                                    "SO_CARGO_QTY_MT" : {{ $value->{"SALES_ORDER_DATA"}->{"SO_CARGO_QTY_MT"} }},
                                                    "SO_ETA" : "{{ $value->{"SALES_ORDER_DATA"}->{"SO_ETA"} }}",
                                                    "SO_ETD" : "{{ $value->{"SALES_ORDER_DATA"}->{"SO_ETD"} }}",
                                                    "CURRENCY_ID" : "{{ $value->{"SALES_ORDER_DATA"}->{"CURRENCY_ID"} }}"
                                                };
                                            </script>
                                            {{-- <td class="align-middle white-space-nowrap py-0"><img onclick="window.location='{{ base_url() }}/ports/{{ $value->PORT_DATA->PORT_ID }}'"  src="{{ env('GO_URL') }}/api/ports/{{ md5($value->PORT_ID) }}/image" style="object-fit: cover;" alt="{{ $value->PORT_ID }}" onerror="this.onerror=null; this.src='{{ base_url() }}/assets/jsb/logo_jsb_blue.png'" width="53" /></td> --}}
                                            <td class="total align-middle fw-bold text-1000"><a class="fw-semi-bold mb-0 line-clamp-2" href="{{ base_url() }}/cart/{{ md5($value->CART_ID) }}"><b>{{ $value->SALES_ORDER_DATA->SO_CODE }}</b></a></td>
                                            <td class="products align-middle">{{ $value->PORT_DATA->PORT_NAME }}</td>
                                            <td class="align-middle white-space-nowrap fs--1 text-900">{{ tglInggris($value->SALES_ORDER_DATA->SO_DOCUMENT_STATUS_DATE, "SHORT") }}</td>
                                            <td class="color align-middle white-space-nowrap fs--1 text-900">{{ $value->SALES_ORDER_DATA->CURRENCY_ID }}</td>
                                            <td class="color align-middle white-space-nowrap fs--1 fw-bold text-900">{{ number_format($displayTotal,2) }}</td>
                                            <td class="align-middle white-space-nowrap text-end pe-0 ps-3">
                                                <!-- <button onClick="deleteItem('{{ md5($value->{'CART_ID'}) }}')" class="btn btn-sm text-500 hover-text-600 me-2"><span class="fas fa-trash"></span></button> -->
                                                <?php
                                                $flagUpdateDetails = false;
                                                if($value->{"SALES_ORDER_DATA"}->{"SO_VESSEL_NAME"} == "" || strtolower($value->{"SALES_ORDER_DATA"}->{"SO_VESSEL_NAME"}) == "vessel name tbd") {
                                                    $flagUpdateDetails = true;
                                                }
                                                if($value->{"SALES_ORDER_DATA"}->{"SO_VESSEL_FLAG"} == "" || strtolower($value->{"SALES_ORDER_DATA"}->{"SO_VESSEL_FLAG"}) == "vessel flag tbd") {
                                                    $flagUpdateDetails = true;
                                                }
                                                if(strtolower($value->{"SALES_ORDER_DATA"}->{"SO_VESSEL_FLAG"}) == "non-indonesia" && $value->{"SALES_ORDER_DATA"}->{"SO_VESSEL_COUNTRY"} == "") {
                                                    $flagUpdateDetails = true;
                                                }
                                                ?>
                                                &nbsp;
                                                @if($flagUpdateDetails)
                                                    <button class="btn btn-sm btn-danger" type="button" onclick="window.location='{{ base_url() }}/cart/{{ md5($value->CART_ID) }}'">Update Details Needed</button>
                                                @else
                                                    <button class="btn btn-sm btn-primary" type="button" onclick="window.location='{{ base_url() }}/cart/{{ md5($value->CART_ID) }}'">Details</button>
                                                    <!-- &nbsp; -->
                                                    <!-- <button class="btn btn-success" type="button" data-bs-toggle="modal" data-bs-target="#mdlConfirm" onclick="checkoutById('{{ md5($value->CART_ID) }}')">Checkout Now</button> -->
                                                @endif
                                            </td>
                                            <td class="align-middle white-space-nowrap text-end pe-0 ps-3">
                                                <div class="font-sans-serif btn-reveal-trigger position-static">
                                                    <button class="btn btn-sm dropdown-toggle dropdown-caret-none transition-none btn-reveal fs--2" type="button" data-bs-toggle="dropdown" data-boundary="window" aria-haspopup="true" aria-expanded="false" data-bs-reference="parent">
                                                        <span class="fas fa-ellipsis-h fs--2"></span>&nbsp; More Actions
                                                    </button>
                                                    <div class="dropdown-menu dropdown-menu-end py-2">
                                                        <a class="dropdown-item" href="javascript:confirmCheckout('{{ md5($value->CART_ID) }}')">Checkout Now</a>
                                                        <a class="dropdown-item" href="javascript:copyCartForm(rowData_{{ md5($value->{'CART_ID'}) }})">Copy to Other Port</a>
                                                        <div class="dropdown-divider"></div>
                                                        <a class="dropdown-item text-danger" href="javascript:deleteItem('{{ md5($value->{'CART_ID'}) }}')">Delete</a>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>

                                        @php $grandTotalIDR += $totalIDR; @endphp
                                        @php $grandTotalUSD += $totalUSD; @endphp
                                    @endforeach
                                @endif

                                <!-- <tr class="cart-table-row btn-reveal-trigger">
                                    <td class="text-1100 fw-semi-bold ps-0 fs-0" colspan="4">Items subtotal :</td>
                                    <td class="text-1100 fw-bold text-end fs-0"></td>
                                    <td></td>
                                </tr> -->
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            @if(isset($ctlCarts->CART_DATA))
                <div class="col-12 col-lg-12" id="divSummary" style="display:none;">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex flex-between-center mb-3">
                                <h3 class="card-title mb-0">Summary</h3>
                            </div>

                            <div class="d-flex justify-content-between border-y border-dashed py-3 mb-0">
                                <h4 class="mb-0">Total</h4>
                                <h4 class="mb-">{{ $value->SALES_ORDER_DATA->CURRENCY_ID }} {{ ($value->SALES_ORDER_DATA->CURRENCY_ID == "IDR") ? number_format($grandTotalIDR, 2, ".", ",") : number_format($grandTotalUSD, 2, ".", ",") }}</h4>
                            </div>
                            <button onClick="checkout()" class="btn btn-primary w-100">CHECKOUT<span class="fas fa-chevron-right ms-1 fs--2"></span></button>
                        </div>
                    </div>
                </div>
            @endif
        </div>
    </div><!-- end of .container-->

    <!-- modal -->
    <div class="modal fade" id="mdlConfirm" tabindex="-1" data-bs-backdrop="static" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-primary">
                    <h5 class="modal-title text-white" id="staticBackdropLabel">CONFIRM CHECKOUT</h5>
                    <button class="btn p-1" type="button" data-bs-dismiss="modal" aria-label="Close"><span class="fas fa-times fs--1 text-white"></span></button>
                </div>
                <div class="modal-body">
                    <p class="text-700 lh-lg mb-0">This action will confirm the order upon your approval for confirming the official order to Port Quanta and will take immediate action accordingly.</p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-primary" type="button" onClick="processCheckoutById()">CONFIRM</button>
                    <button class="btn btn-outline-danger" type="button" data-bs-dismiss="modal">CANCEL</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="mdlCopyCart" tabindex="-1" aria-labelledby="modalFormLabel" style="display: none;" aria-hidden="true">
        <div class="modal-dialog modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalFormLabel">Copy to Other Port</h5>
                    <button class="btn p-1" type="button" data-bs-dismiss="modal" aria-label="Close"><svg class="svg-inline--fa fa-xmark fs--1" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="xmark" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512" data-fa-i2svg=""><path fill="currentColor" d="M310.6 361.4c12.5 12.5 12.5 32.75 0 45.25C304.4 412.9 296.2 416 288 416s-16.38-3.125-22.62-9.375L160 301.3L54.63 406.6C48.38 412.9 40.19 416 32 416S15.63 412.9 9.375 406.6c-12.5-12.5-12.5-32.75 0-45.25l105.4-105.4L9.375 150.6c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0L160 210.8l105.4-105.4c12.5-12.5 32.75-12.5 45.25 0s12.5 32.75 0 45.25l-105.4 105.4L310.6 361.4z"></path></svg><!-- <span class="fas fa-times fs--1"></span> Font Awesome fontawesome.com --></button>
                </div>
                
                <div class="modal-body">
                    <div class="mb-2" style="font-size: 93%;">
                        All fields are <b>mandatory</b>.
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-2">
                                <label class="form-label" for="divExistingPort">From Port</label>
                                <div style="padding-left: 1rem;" class="fw-bold" id="divExistingPort"></div>
                                <input type="hidden" id="portIdExisting" value=""/>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-2">
                                <label class="form-label" for="portId">To Port</label>
                                <select class="form-select" id="portId" >
                                    @foreach($ctlPorts as $aPort)
                                        <option value='{{ $aPort->{"PORT_ID"} }}'>{{ $aPort->{"PORT_NAME"} }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="mb-2" style="display:block;">
                        <label class="form-label" for="vesselName">Vessel Name</label>
                        <input class="form-control" id="vesselName" type="text" value="" style="text-transform: uppercase;" />
                    </div>
                    
                    <div class="mb-2" style="display:block;">
                        <label class="form-label" for="vesselFlag"><b>Vessel Flag</b> &nbsp;<span style="color:red; font-size: 105%;">*</span></label>
                        <select class="form-select" id="vesselFlag">
                            <option value='Indonesia'>Indonesia</option>
                            <option value='Non-Indonesia'>Non-Indonesia</option>
                        </select>
                    </div>
          
                    <div class="mb-2" id="divVesselCountry" style="display:none;">
                        <label class="form-label" for="vesselCountry">Vessel Country <!--&nbsp;<span style="color:red; font-size: 105%;">*</span>--></label>
                        <input class="form-control" id="vesselCountry" type="text" value="INDONESIA"  style="text-transform: uppercase;" />
                    </div>

                    <div class="mb-2" style="display:block;">
                        <label class="form-label" for="voyageNo">Voyage No.</label>
                        <input class="form-control" id="voyageNo" type="text" value="" style="text-transform: uppercase;" />
                    </div>
          
                    <div class="mb-2">
                        <label class="form-label" for="vesselGRT">Vessel GRT <!--&nbsp;<span style="color:red; font-size: 105%;">*</span--></label>
                        <input class="form-control numeric-input-no-sign" id="vesselGRT" type="text"   />
                    </div>

                    <div class="mb-2">
                        <label class="form-label" for="vesselDWT">Vessel DWT <!--&nbsp;<span style="color:red; font-size: 105%;">*</span--></label>
                        <input class="form-control numeric-input-no-sign" id="vesselDWT" type="text"   />
                    </div>
                    
          
                    <div class="mb-2">
                        <label class="form-label" for="vesselLOA">Vessel LOA in Meter</label>
                        <input class="form-control numeric-input-no-sign-decimal-2" id="vesselLOA" type="text"   />
                    </div>
          
                    <div class="mb-2">
                        <label class="form-label" for="cargoQtyMT">Cargo Qty MT</label>
                        <input class="form-control numeric-input-no-sign" id="cargoQtyMT" type="text"   />
                    </div>

                    <div class="mb-2">
                        <label class="form-label" for="vesselShipment">Shipment Type</label>
                        <select class="form-select" id="vesselShipment" >
                            <option value='Import/Export'>Import/Export</option>
                            <option value='Local (Domestic)'>Local (Domestic)</option>
                        </select>
                    </div>

                    <div class="mb-2">
                        <label class="form-label" for="operation">Operation</label>
                        <select class="form-select" id="operation" >
                            @foreach($ctlRefOperation as $k => $value)
                                @if($value != "-" && $value != "")
                                    <option value='{{ $value }}'>{{ $value }}</option>
                                @endif
                            @endforeach
                        </select>
                    </div>

                    <div class="mb-2" style="display:none;">
                        <label class="form-label" for="note">Note</label>
                        <input class="form-control" id="note" type="text"/>
                    </div>
          
                    <div class="mb-2" style="display:block;">
                        <label class="form-label" for="eta">ETA</label>
                        <input class="form-control datetimepicker" id="eta" type="text" placeholder="yyyy-mm-dd" data-options='{"enableTime":true,"dateFormat":"Y-m-d H:i","disableMobile":true}' />
                    </div>
          
                    <div class="mb-2" style="display:block;">
                        <label class="form-label" for="etd">ETD</label>
                        <input class="form-control datetimepicker" id="etd" type="text" placeholder="yyyy-mm-dd" data-options='{"enableTime":true,"dateFormat":"Y-m-d H:i","disableMobile":true}' />
                    </div>
          
                    <div class="mb-2" style="display:none;">
                        <label class="form-label" for="currencyId">Currency</label>
                        <select class="form-select" id="currencyId" >
                            <option value='USD'>USD</option>    
                            <option value='IDR'>IDR</option>
                        </select>
                    </div>

                    <div class="modal-footer">
                        <button class="btn btn-primary" type="button" onclick="processCopyCart()">PROCEED</button>
                        <button class="btn btn-outline-danger" type="button" data-bs-dismiss="modal">CANCEL</button>
                    </div>
                </div>
            </div>
        </div>  
    </div>

@endsection

@section('script')
    <script type="text/javascript">
        var gSelectedId = "";

        @if ($errors->any())
            toastr.error("{{ $errors->first() }}");
        @endif

        function deleteItem(id) {
            createOverlay("Processing...");
            $.ajax({
                type: "GET",
                url: "{{ base_url() }}/token",
                data: "",
                success: function(data) {
                    if (data["STATUS"] == "SUCCESS") {
                        var token = data["PAYLOAD"];

                        $.ajax({
                            type: "POST",
                            url: "{{ base_url() }}/cart/delete",
                            data: {
                                "id" : id,
                                "_token": token
                            },
                            success: function(data) {
                                gOverlay.hide();
                                if (data["STATUS"] == "SUCCESS") {
                                    toastr.success(data["MESSAGE"]);
                                    setTimeout(function() {
                                        window.location = "{{ base_url() }}/cart";
                                    }, 500);
                                } 
                                else {
                                    toastr.error(data["MESSAGE"]);
                                }
                            },
                            error: function(error) {
                                gOverlay.hide();
                                toastr.error("Network/server error\r\n" + error);
                            }
                        });
                    } 
                    else {
                        gOverlay.hide();
                        toastr.error(data["MESSAGE"]);
                    }
                },
                error: function(error) {
                    gOverlay.hide();
                    toastr.error("Network/server error " + error);
                }
            });
        }

        function confirmCheckout(cartIdHashed) {
            checkoutById(cartIdHashed);
            $("#mdlConfirm").modal("show");
        }

        function checkoutById(cartIdHashed) {
            gSelectedId = cartIdHashed;
        }
        
        function processCheckoutById() {
            if(gSelectedId == "") {
                toastr.error("Select order to checkout");
                return;
            }

            $("#mdlConfirm").modal("hide");
            createOverlay("Processing...");
            $.ajax({
                type: "GET",
                url: "{{ base_url() }}/token",
                data: "",
                success: function(data) {
                    if (data["STATUS"] == "SUCCESS") {
                        var token = data["PAYLOAD"];

                        $.ajax({
                            type: "POST",
                            url: "{{ base_url() }}/cart/checkout/" + gSelectedId,
                            data: {
                                "_token": token
                            },
                            success: function(data) {
                                gOverlay.hide();
                                if (data["STATUS"] == "SUCCESS") {
                                    toastr.success(data["MESSAGE"]);
                                    setTimeout(function() {
                                        window.location = "{{ base_url() }}/orders";
                                    }, 500);
                                } 
                                else {
                                    $("#mdlConfirm").modal("hide");
                                    toastr.error(data["MESSAGE"]);
                                }
                            },
                            error: function(error) {
                                gOverlay.hide();
                                toastr.error("Network/server error\r\n" + error);
                            }
                        });
                    } else {
                        gOverlay.hide();
                        toastr.error(data["MESSAGE"]);
                    }
                },
                error: function(error) {
                    gOverlay.hide();
                    toastr.error("Network/server error " + error);
                }
            });
        }

        function checkout() {
            createOverlay("Processing...");
            $.ajax({
                type: "GET",
                url: "{{ base_url() }}/token",
                data: "",
                success: function(data) {
                    if (data["STATUS"] == "SUCCESS") {
                        var token = data["PAYLOAD"];

                        $.ajax({
                            type: "POST",
                            url: "{{ base_url() }}/cart/checkout",
                            data: {
                                "_token": token
                            },
                            success: function(data) {
                                gOverlay.hide();
                                if (data["STATUS"] == "SUCCESS") {
                                    toastr.success(data["MESSAGE"]);
                                    setTimeout(function() {
                                        window.location = "{{ base_url() }}/orders?documentStatus=inquiry";
                                    }, 500);
                                } else {
                                    toastr.error(data["MESSAGE"]);
                                }
                            },
                            error: function(error) {
                                gOverlay.hide();
                                toastr.error("Network/server error\r\n" + error);
                            }
                        });
                    } else {
                        gOverlay.hide();
                        toastr.error(data["MESSAGE"]);
                    }
                },
                error: function(error) {
                    gOverlay.hide();
                    toastr.error("Network/server error " + error);
                }
            });
        }

        $('#vesselFlag').on('change', function() {
            if(this.value == "Indonesia"){
                $('#vesselCountry').val("INDONESIA")
                $('#divVesselCountry').css("display", "none");
            }
            else {
                $('#vesselCountry').val("")
                $('#divVesselCountry').css("display", "block");
            }
        });

        function copyCartForm(rowData) {
            $("#divExistingPort").html(rowData.PORT_NAME);
            $("#portIdExisting").val(rowData.PORT_ID);
            $("#vesselName").val(rowData.SO_VESSEL_NAME);
            $("#vesselFlag").val(rowData.SO_VESSEL_FLAG).trigger("change");
            $("#vesselCountry").val(rowData.SO_VESSEL_COUNTRY);
            $("#vesselDWT").autoNumeric("set", rowData.SO_VESSEL_DWT);
            $("#vesselGRT").autoNumeric("set", rowData.SO_VESSEL_GRT);
            $("#vesselLOA").autoNumeric("set", rowData.SO_VESSEL_LOA);
            $("#operation").val(rowData.SO_OPERATION).trigger("change");
            $("#vesselShipment").val(rowData.SO_VESSEL_SHIPMENT).trigger("change");
            $("#voyageNo").val(rowData.SO_VOYAGE_NO);
            $("#cargoQtyMT").autoNumeric("set", rowData.SO_CARGO_QTY_MT);
            $("#eta").val(rowData.SO_ETA);
            $("#etd").val(rowData.SO_ETD);
            $("#currencyId").val(rowData.CURRENCY_ID).trigger("change");

            $("#mdlCopyCart").modal("show");
        }

        function processCopyCart() {
            var portIdExisting = $("#portIdExisting").val();
            var portId = $("#portId").val();
            var vesselName = $("#vesselName").val();
            var vesselCountry = $("#vesselCountry").val();
            var vesselFlag = $("#vesselFlag").val();
            var vesselGRT = $("#vesselGRT").autoNumeric("get");
            var vesselDWT = $("#vesselDWT").autoNumeric("get");
            var vesselLOA = $("#vesselLOA").autoNumeric("get");
            var cargoQtyMT = $("#cargoQtyMT").autoNumeric("get");
            var vesselShipment = $("#vesselShipment").val();
            var operation = $("#operation").val();
            var eta = $("#eta").val();
            var etd = $("#etd").val();
            var note = $("#note").val();
            var currencyId = $("#currencyId").val();
            var voyageNo = $("#voyageNo").val();
            
            if (portId == "") {
                toastr.error("Please select port to copy");
                return;
            }

            if (portIdExisting != "" && portIdExisting == portId) {
                toastr.error("Port source and destination must be different");
                return;
            }

            if (vesselName == "") {
                toastr.error("Please input Vessel Name");
                return;
            }
            if(vesselCountry == "") {
                if(vesselFlag == "Indonesia") {
                    vesselCountry = "INDONESIA"
                }
                else {
                    toastr.error("Please input Vessel Country");
                    return;
                }
            }
            if (vesselGRT == "0" || vesselGRT.trim() == ""){
                toastr.error("Please input Vessel GRT");
                return;
            }
            if (vesselDWT == "0" || vesselDWT.trim() == ""){
                toastr.error("Please input Vessel DWT");
                return;
            }
            if (vesselLOA == "0" || vesselLOA.trim() == ""){
                toastr.error("Please input Vessel LOA");
                return;
            }
            if (cargoQtyMT == "0" || cargoQtyMT.trim() == ""){
                toastr.error("Please input Cargo Qty MT");
                return;
            }
            if (etd.trim() == ""){
                toastr.error("Please input ETD");
                return;
            }
            if (eta.trim() == ""){
                toastr.error("Please input ETA");
                return;
            }
            if (voyageNo.trim() == "") {
                toastr.error("Please input voyage number");
                return;
            }

            $("#mdlCopyCart").modal("hide");

            createOverlay("Processing...");
            $.ajax({
                type: "GET",
                url: "{{ base_url() }}/token",
                data: "",
                success: function(data) {
                    if (data["STATUS"] == "SUCCESS") {
                        let token = data["PAYLOAD"];

                        $.ajax({
                            type: "POST",
                            url: "{{ base_url() }}/ports/" + portId + "/add-to-cart",
                            data: {
                                "vesselName" : vesselName,
                                "vesselFlag" : vesselFlag,
                                "vesselCountry" : vesselCountry,
                                "vesselGRT": vesselGRT,
                                "vesselDWT" : vesselDWT,
                                "vesselLOA": vesselLOA,
                                "cargoQtyMT": cargoQtyMT,
                                "vesselShipment" : vesselShipment,
                                "operation" : operation,
                                "eta" : eta,
                                "etd" : etd,
                                "note" : note,
                                "currencyId" : currencyId,
                                "voyageNo" : voyageNo,
                                "_token": token
                            },
                            success: function(data) {
                                gOverlay.hide();
                                if (data["STATUS"] == "SUCCESS") {
                                    toastr.success(data["MESSAGE"]);
                                    window.location.reload();
                                } 
                                else {
                                    $("#mdlCopyCart").modal("show");
                                    toastr.error(data["MESSAGE"]);
                                }
                            },
                            error: function(error) {
                                gOverlay.hide();
                                $("#mdlCopyCart").modal("show");
                                toastr.error("Network/server error\r\n" + error);
                            }
                        });
                    } 
                    else {
                        gOverlay.hide();
                        $("#mdlCopyCart").modal("show");
                        toastr.error(data["MESSAGE"]);
                    }
                },
                error: function(error) {
                    gOverlay.hide();
                    $("#mdlCopyCart").modal("show");
                    toastr.error("Network/server error " + error);
                }
            });
        }
    </script>
@endsection
